In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_excel('preprocessed data.xlsx')

In [3]:
df.head()

target  tumor size  node status of the tumor  Age of the patient  \
0       0           2                         1                  60   
1       0           1                         1                  55   
2       0           1                         1                  33   
3       0           1                         1                  67   
4       0           1                         1                  47   

   tumor grade  
0            3  
1            2  
2            3  
3            2  
4            2

In [4]:
df.describe()

target  tumor size  node status of the tumor  Age of the patient  \
count  234.000000  234.000000                234.000000          234.000000   
mean     0.183761    1.944444                  0.705128           48.974359   
std      0.388119    0.525234                  0.670193           10.551294   
min      0.000000    1.000000                  0.000000           25.000000   
25%      0.000000    2.000000                  0.000000           41.000000   
50%      0.000000    2.000000                  1.000000           49.000000   
75%      0.000000    2.000000                  1.000000           56.750000   
max      1.000000    3.000000                  3.000000           75.000000   

       tumor grade  
count   234.000000  
mean      2.598291  
std       0.533188  
min       1.000000  
25%       2.000000  
50%       3.000000  
75%       3.000000  
max       3.000000

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_res = df.iloc[:,1:].values
y_res = df.iloc[:,0].values

In [7]:
X_res

array([[ 2,  1, 60,  3],
       [ 1,  1, 55,  2],
       [ 1,  1, 33,  3],
       [ 1,  1, 67,  2],
       [ 1,  1, 47,  2],
       [ 1,  1, 40,  3],
       [ 1,  1, 45,  2],
       [ 1,  1, 26,  2],
       [ 1,  1, 65,  3],
       [ 1,  1, 58,  2],
       [ 1,  1, 61,  2],
       [ 1,  1, 35,  3],
       [ 1,  1, 48,  3],
       [ 1,  1, 60,  3],
       [ 1,  1, 47,  3],
       [ 1,  1, 56,  3],
       [ 2,  1, 56,  2],
       [ 2,  1, 46,  3],
       [ 2,  1, 33,  2],
       [ 2,  1, 38,  2],
       [ 2,  1, 69,  3],
       [ 2,  1, 45,  3],
       [ 2,  1, 53,  3],
       [ 2,  0, 55,  2],
       [ 2,  0, 54,  2],
       [ 2,  0, 30,  2],
       [ 2,  0, 50,  3],
       [ 2,  0, 38,  3],
       [ 2,  0, 43,  3],
       [ 2,  0, 40,  3],
       [ 2,  0, 60,  3],
       [ 2,  0, 48,  3],
       [ 2,  0, 41,  3],
       [ 2,  0, 53,  2],
       [ 2,  0, 50,  2],
       [ 2,  0, 45,  3],
       [ 2,  0, 58,  2],
       [ 2,  0, 60,  3],
       [ 2,  0, 34,  2],
       [ 2,  0, 55,  3],


In [8]:
y_res

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
from imblearn.over_sampling import RandomOverSampler

Using TensorFlow backend.


In [10]:
os = RandomOverSampler()
X_res,y_res = os.fit_sample(X_res,y_res)

In [11]:
X_res.shape

(382, 4)

In [12]:
y_res.shape

(382,)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X_res,y_res, test_size=0.2, random_state=42)

In [14]:
from sklearn.preprocessing import Normalizer

In [15]:
scaler = Normalizer().fit(X_train)
standarized_x = scaler.transform(X_train)
standarized_x_test = scaler.transform(X_test)

In [16]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [17]:
model = SVC()

In [18]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.38961038961038963
[[ 0 47]
 [ 0 30]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        47
           1       0.39      1.00      0.56        30

    accuracy                           0.39        77
   macro avg       0.19      0.50      0.28        77
weighted avg       0.15      0.39      0.22        77



/home/nitin/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(standarized_x,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [20]:
y_pred = classifier.predict(standarized_x_test)

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [22]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [23]:
accuracy

0.38961038961038963

In [24]:
# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [1, 10, 100, 1000,10000,100000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000,10000,100000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(standarized_x,y_train)

In [25]:
accuracy = grid_search.best_score_

In [26]:
accuracy

0.6720430107526882

In [27]:
grid_search.best_params_

{'C': 100000, 'gamma': 0.4, 'kernel': 'rbf'}

In [33]:
classifier = SVC(C=10000 ,kernel = 'rbf', gamma=0.4)
classifier.fit(standarized_x,y_train)

SVC(C=10000, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.4, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [34]:
y_pred = classifier.predict(standarized_x_test)

In [35]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [36]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [37]:
accuracy

0.6233766233766234