In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_excel('preprocessed data.xlsx')

In [3]:
df.describe()

Unnamed: 0      sl.no.  \
count  234.000000  234.000000   
mean   116.500000  117.500000   
std     67.694165   67.694165   
min      0.000000    1.000000   
25%     58.250000   59.250000   
50%    116.500000  117.500000   
75%    174.750000  175.750000   
max    233.000000  234.000000   

       0- Good Outcome/no recurrence\n1- Bad Outcome/recurrence  tumor size  \
count                                         234.000000         234.000000   
mean                                            0.183761           1.944444   
std                                             0.388119           0.525234   
min                                             0.000000           1.000000   
25%                                             0.000000           2.000000   
50%                                             0.000000           2.000000   
75%                                             0.000000           2.000000   
max                                             1.000000           3.000000   

       node status of the tumor  Age of the patient  tumor grade        A%-M  \
count                234.000000          234.000000   234.000000  234.000000   
mean                   0.705128           48.974359     2.598291    6.581197   
std                    0.670193           10.551294     0.533188   17.617168   
min                    0.000000           25.000000     1.000000    0.000000   
25%                    0.000000           41.000000     2.000000    0.000000   
50%                    1.000000           49.000000     3.000000    0.000000   
75%                    1.000000           56.750000     3.000000    0.000000   
max                    3.000000           75.000000     3.000000   80.000000   

             AI-M        A%-C  ...        R%-C        U%-C        V%-C  \
count  234.000000  234.000000  ...  234.000000  234.000000  234.000000   
mean     1.737179   29.102564  ...   73.846154   75.320513   71.559829   
std      0.849354   30.409335  ...    6.804587    6.232602    7.427955   
min      0.000000    0.000000  ...   60.000000   55.000000   50.000000   
25%      1.500000    0.000000  ...   70.000000   70.000000   70.000000   
50%      2.000000   20.000000  ...   75.000000   75.000000   70.000000   
75%      2.000000   60.000000  ...   80.000000   80.000000   75.000000   
max      3.000000   80.000000  ...   90.000000   90.000000   90.000000   

             W%-M        W%-C      ZA1%-M      ZA1%-C       ZB%-C       ZC%-C  \
count  234.000000  234.000000  234.000000  234.000000  234.000000  234.000000   
mean    69.401709   70.170940   74.615385   70.170940   72.264957   76.303419   
std     10.454528    8.957018    6.457316    8.957018    8.491241    5.851326   
min     40.000000   40.000000   55.000000   40.000000   50.000000   55.000000   
25%     65.000000   65.000000   70.000000   65.000000   70.000000   71.250000   
50%     70.000000   70.000000   75.000000   70.000000   70.000000   80.000000   
75%     75.000000   78.750000   80.000000   78.750000   80.000000   80.000000   
max     95.000000   85.000000   90.000000   85.000000   85.000000   90.000000   

            ZD%-C  
count  234.000000  
mean    74.914530  
std      5.913646  
min     55.000000  
25%     70.000000  
50%     75.000000  
75%     80.000000  
max     85.000000  

[8 rows x 87 columns]

In [4]:
df['0- Good Outcome/no recurrence\n1- Bad Outcome/recurrence'].value_counts()

0    191
1     43
Name: 0- Good Outcome/no recurrence\n1- Bad Outcome/recurrence, dtype: int64

In [5]:
from imblearn.under_sampling import NearMiss

Using TensorFlow backend.


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_res = df.iloc[:,3:].values
y_res = df.iloc[:,2].values

In [8]:
nm = NearMiss()
X_res,y_res = nm.fit_sample(X_res,y_res)

In [9]:
X_res.shape

(86, 84)

In [10]:
y_res.shape

(86,)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X_res,y_res, test_size=0.2, random_state=42)

In [12]:
from sklearn.preprocessing import Normalizer

In [13]:
scaler = Normalizer().fit(X_train)
standarized_x = scaler.transform(X_train)
standarized_x_test = scaler.transform(X_test)

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [15]:
model = RandomForestClassifier()

In [16]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7777777777777778
[[6 1]
 [3 8]]
              precision    recall  f1-score   support

           0       0.67      0.86      0.75         7
           1       0.89      0.73      0.80        11

    accuracy                           0.78        18
   macro avg       0.78      0.79      0.77        18
weighted avg       0.80      0.78      0.78        18



In [17]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [18]:
model = GaussianNB()

In [19]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7777777777777778
[[7 0]
 [4 7]]
              precision    recall  f1-score   support

           0       0.64      1.00      0.78         7
           1       1.00      0.64      0.78        11

    accuracy                           0.78        18
   macro avg       0.82      0.82      0.78        18
weighted avg       0.86      0.78      0.78        18



In [20]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [21]:
model = SVC()

In [22]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7222222222222222
[[7 0]
 [5 6]]
              precision    recall  f1-score   support

           0       0.58      1.00      0.74         7
           1       1.00      0.55      0.71        11

    accuracy                           0.72        18
   macro avg       0.79      0.77      0.72        18
weighted avg       0.84      0.72      0.72        18



In [23]:
from sklearn import neighbors
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [24]:
model = neighbors.KNeighborsClassifier(3)

In [25]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7222222222222222
[[7 0]
 [5 6]]
              precision    recall  f1-score   support

           0       0.58      1.00      0.74         7
           1       1.00      0.55      0.71        11

    accuracy                           0.72        18
   macro avg       0.79      0.77      0.72        18
weighted avg       0.84      0.72      0.72        18



In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
model = LogisticRegression()

In [28]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6666666666666666
[[7 0]
 [6 5]]
              precision    recall  f1-score   support

           0       0.54      1.00      0.70         7
           1       1.00      0.45      0.62        11

    accuracy                           0.67        18
   macro avg       0.77      0.73      0.66        18
weighted avg       0.82      0.67      0.65        18



In [29]:
import xgboost as xgb
xgb_model = xgb.XGBClassifier(objective='binary:logistic')
xgb_model.fit(standarized_x,y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [30]:
y_pred = xgb_model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8888888888888888
[[ 6  1]
 [ 1 10]]
              precision    recall  f1-score   support

           0       0.86      0.86      0.86         7
           1       0.91      0.91      0.91        11

    accuracy                           0.89        18
   macro avg       0.88      0.88      0.88        18
weighted avg       0.89      0.89      0.89        18

