In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_excel('preprocessed data.xlsx')

In [3]:
df.head()

Unnamed: 0  sl.no.  \
0           0       1   
1           1       2   
2           2       3   
3           3       4   
4           4       5   

   0- Good Outcome/no recurrence\n1- Bad Outcome/recurrence  tumor size  \
0                                                  0                  2   
1                                                  0                  1   
2                                                  0                  1   
3                                                  0                  1   
4                                                  0                  1   

   node status of the tumor  Age of the patient  tumor grade  A%-M  AI-M  \
0                         1                  60            3     0   2.5   
1                         1                  55            2    15   2.0   
2                         1                  33            3     0   2.5   
3                         1                  67            2     0   2.0   
4                         1                  47            2     0   0.0   

   A%-C  ...  R%-C  U%-C  V%-C  W%-M  W%-C  ZA1%-M  ZA1%-C  ZB%-C  ZC%-C  \
0    70  ...    70    80    75    70    60      85      60     80     85   
1    20  ...    75    80    75    80    60      85      60     80     80   
2    70  ...    60    75    70    70    70      55      70     75     80   
3    45  ...    70    75    60    45    70      60      70     75     80   
4     0  ...    75    75    80    70    75      85      75     80     80   

   ZD%-C  
0     70  
1     80  
2     75  
3     80  
4     80  

[5 rows x 87 columns]

In [4]:
df['0- Good Outcome/no recurrence\n1- Bad Outcome/recurrence'].value_counts()

0    191
1     43
Name: 0- Good Outcome/no recurrence\n1- Bad Outcome/recurrence, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_res = df.iloc[:,3:].values
y_res = df.iloc[:,2].values

In [7]:
X_res.shape

(234, 84)

In [8]:
y_res.shape

(234,)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_res,y_res, test_size=0.2, random_state=42)

In [10]:
from sklearn.preprocessing import Normalizer

In [11]:
scaler = Normalizer().fit(X_train)
standarized_x = scaler.transform(X_train)
standarized_x_test = scaler.transform(X_test)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [13]:
model = RandomForestClassifier()

In [14]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7446808510638298
[[35  0]
 [12  0]]
              precision    recall  f1-score   support

           0       0.74      1.00      0.85        35
           1       0.00      0.00      0.00        12

    accuracy                           0.74        47
   macro avg       0.37      0.50      0.43        47
weighted avg       0.55      0.74      0.64        47



/home/nitin/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [16]:
model = GaussianNB()

In [17]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6170212765957447
[[25 10]
 [ 8  4]]
              precision    recall  f1-score   support

           0       0.76      0.71      0.74        35
           1       0.29      0.33      0.31        12

    accuracy                           0.62        47
   macro avg       0.52      0.52      0.52        47
weighted avg       0.64      0.62      0.63        47



In [18]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [19]:
model = SVC()

In [20]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7446808510638298
[[35  0]
 [12  0]]
              precision    recall  f1-score   support

           0       0.74      1.00      0.85        35
           1       0.00      0.00      0.00        12

    accuracy                           0.74        47
   macro avg       0.37      0.50      0.43        47
weighted avg       0.55      0.74      0.64        47



/home/nitin/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [21]:
from sklearn import neighbors
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [22]:
model = neighbors.KNeighborsClassifier(3)

In [23]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.723404255319149
[[33  2]
 [11  1]]
              precision    recall  f1-score   support

           0       0.75      0.94      0.84        35
           1       0.33      0.08      0.13        12

    accuracy                           0.72        47
   macro avg       0.54      0.51      0.48        47
weighted avg       0.64      0.72      0.66        47



In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
model = LogisticRegression()

In [26]:
model.fit(standarized_x,y_train)
y_pred = model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7446808510638298
[[35  0]
 [12  0]]
              precision    recall  f1-score   support

           0       0.74      1.00      0.85        35
           1       0.00      0.00      0.00        12

    accuracy                           0.74        47
   macro avg       0.37      0.50      0.43        47
weighted avg       0.55      0.74      0.64        47



/home/nitin/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
import xgboost as xgb
xgb_model = xgb.XGBClassifier(objective='binary:logistic')
xgb_model.fit(standarized_x,y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [28]:
y_pred = xgb_model.predict(standarized_x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7446808510638298
[[34  1]
 [11  1]]
              precision    recall  f1-score   support

           0       0.76      0.97      0.85        35
           1       0.50      0.08      0.14        12

    accuracy                           0.74        47
   macro avg       0.63      0.53      0.50        47
weighted avg       0.69      0.74      0.67        47

