In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_excel("preprocessed data.xlsx")

In [2]:
def dataSetAnalysis(df):
    #view starting values of data set
    print("Dataset Head")
    print(df.head(3))
    print("=" * 100)
    
    # View features in data set
    print("Dataset Features")
    print(df.columns.values)
    print("=" * 100)
    
    # View How many samples and how many missing values for each feature
    print("Dataset Features Details")
    print(df.info())
    print("=" * 100)
    
    # view distribution of numerical features across the data set
    print("Dataset Numerical Features")
    print(df.describe())
    print("=" * 100)
    
    

In [3]:
dataSetAnalysis(df)

Dataset Head
   Unnamed: 0  sl.no.  \
0           0       1   
1           1       2   
2           2       3   

   0- Good Outcome/no recurrence\n1- Bad Outcome/recurrence  tumor size  \
0                                                  0                  2   
1                                                  0                  1   
2                                                  0                  1   

   node status of the tumor  Age of the patient  tumor grade  A%-M  AI-M  \
0                         1                  60            3     0   2.5   
1                         1                  55            2    15   2.0   
2                         1                  33            3     0   2.5   

   A%-C  ...  R%-C  U%-C  V%-C  W%-M  W%-C  ZA1%-M  ZA1%-C  ZB%-C  ZC%-C  \
0    70  ...    70    80    75    70    60      85      60     80     85   
1    20  ...    75    80    75    80    60      85      60     80     80   
2    70  ...    60    75    70    70    70      55  

In [4]:
X = df.iloc[:,3:].values
y = df.iloc[:,2].values


In [5]:
X

array([[ 2.,  1., 60., ..., 80., 85., 70.],
       [ 1.,  1., 55., ..., 80., 80., 80.],
       [ 1.,  1., 33., ..., 75., 80., 75.],
       ...,
       [ 3.,  2., 37., ..., 75., 75., 70.],
       [ 3.,  2., 58., ..., 70., 75., 70.],
       [ 1.,  1., 52., ..., 70., 80., 70.]])

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [8]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential() # Initialising the ANN

classifier.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu', input_dim = 84))
classifier.add(Dense(units = 16, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 8, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 2, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

Using TensorFlow backend.


In [10]:
classifier.compile(optimizer = 'SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [11]:
classifier.fit(X_train, y_train, batch_size = 60, epochs = 50, verbose = 2)

Epoch 1/50
 - 0s - loss: 0.6921 - accuracy: 0.8075
Epoch 2/50
 - 0s - loss: 0.6887 - accuracy: 0.8075
Epoch 3/50
 - 0s - loss: 0.6849 - accuracy: 0.8075
Epoch 4/50
 - 0s - loss: 0.6812 - accuracy: 0.8075
Epoch 5/50
 - 0s - loss: 0.6771 - accuracy: 0.8075
Epoch 6/50
 - 0s - loss: 0.6736 - accuracy: 0.8075
Epoch 7/50
 - 0s - loss: 0.6708 - accuracy: 0.8075
Epoch 8/50
 - 0s - loss: 0.6678 - accuracy: 0.8075
Epoch 9/50
 - 0s - loss: 0.6644 - accuracy: 0.8075
Epoch 10/50
 - 0s - loss: 0.6611 - accuracy: 0.8075
Epoch 11/50
 - 0s - loss: 0.6582 - accuracy: 0.8075
Epoch 12/50
 - 0s - loss: 0.6550 - accuracy: 0.8075
Epoch 13/50
 - 0s - loss: 0.6519 - accuracy: 0.8075
Epoch 14/50
 - 0s - loss: 0.6485 - accuracy: 0.8075
Epoch 15/50
 - 0s - loss: 0.6459 - accuracy: 0.8075
Epoch 16/50
 - 0s - loss: 0.6432 - accuracy: 0.8075
Epoch 17/50
 - 0s - loss: 0.6401 - accuracy: 0.8075
Epoch 18/50
 - 0s - loss: 0.6382 - accuracy: 0.8075
Epoch 19/50
 - 0s - loss: 0.6355 - accuracy: 0.8075
Epoch 20/50
 - 0s - l

In [12]:
from keras.models import load_model

classifier.save('breast_cancer_model.h5') #Save trained ANN
#classifier = load_model('breast_cancer_model.h5')  #Load trained ANN

In [13]:
y_pred = classifier.predict(X_test)
y_pred = [ 1 if y>=0.5 else 0 for y in y_pred ]

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1])
print("Accuracy: "+ str(accuracy*100)+"%")

[[40  0]
 [ 7  0]]
Accuracy: 85.1063829787234%


In [15]:
import sklearn
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [16]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.851063829787234
[[40  0]
 [ 7  0]]
              precision    recall  f1-score   support

           0       0.85      1.00      0.92        40
           1       0.00      0.00      0.00         7

    accuracy                           0.85        47
   macro avg       0.43      0.50      0.46        47
weighted avg       0.72      0.85      0.78        47



/home/nitin/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
